In [1]:
# Importing the necessary libraries.
import pandas as pd
import numpy as np

In [57]:
# Reading the laptop keywords file
df = pd.read_excel(r"C:\Users\Mazahir\Desktop\laptop_keywords_all.xlsx")
df

,Sentences,Keywords
0,I use my laptop as a software engineer to writ...,"software engineer, coding, debugging, testing,..."
1,"As a graphic designer, I use my laptop to crea...","graphic designer, digital art, logo design, ma..."
2,"I use my laptop as a writer to craft stories, ...","writer, storytelling, poetry, manuscript editi..."
3,"As a musician, I use my laptop to compose musi...","musician, music composition, song recording, a..."
4,I use my laptop as a gamer to play online game...,"gamer, online gaming, virtual worlds, competit..."
...,...,...
493,I want a laptop with long battery life and rel...,"long battery life, reliable performance, resea..."
494,I need a laptop to do presentations during lec...,"presentations, lectures"
495,I want a laptop that can connect to interactiv...,"connect to interactive whiteboards, collaborat..."
496,I want a laptop with a long battery life to la...,"long battery life, lectures, teching sessions"
497,I need a lightweight and portable laptop for e...,"lightweight, portable,easy transport"

In [20]:
# removing all the duplicate records
df = df.drop_duplicates()
df

,Sentences,Keywords
0,I use my laptop as a software engineer to writ...,"software engineer, coding, debugging, testing,..."
1,"As a graphic designer, I use my laptop to crea...","graphic designer, digital art, logo design, ma..."
2,"I use my laptop as a writer to craft stories, ...","writer, storytelling, poetry, manuscript editi..."
3,"As a musician, I use my laptop to compose musi...","musician, music composition, song recording, a..."
4,I use my laptop as a gamer to play online game...,"gamer, online gaming, virtual worlds, competit..."
...,...,...
516,I want a laptop with long battery life and rel...,"long battery life, reliable performance, resea..."
517,I need a laptop to do presentations during lec...,"presentations, lectures"
518,I want a laptop that can connect to interactiv...,"connect to interactive whiteboards, collaborat..."
519,I want a laptop with a long battery life to la...,"long battery life, lectures, teching sessions"
520,I need a lightweight and portable laptop for e...,"lightweight, portable,easy transport"

In [36]:
# data type
dtypes_count = df.dtypes.value_counts()
print(dtypes_count)

object    2
Name: count, dtype: int64

In [51]:
# Remove rows with empty cells
df = df.dropna()
df

,Sentences,Keywords
0,I use my laptop as a software engineer to writ...,"software engineer, coding, debugging, testing,..."
1,"As a graphic designer, I use my laptop to crea...","graphic designer, digital art, logo design, ma..."
2,"I use my laptop as a writer to craft stories, ...","writer, storytelling, poetry, manuscript editi..."
3,"As a musician, I use my laptop to compose musi...","musician, music composition, song recording, a..."
4,I use my laptop as a gamer to play online game...,"gamer, online gaming, virtual worlds, competit..."
...,...,...
516,I want a laptop with long battery life and rel...,"long battery life, reliable performance, resea..."
517,I need a laptop to do presentations during lec...,"presentations, lectures"
518,I want a laptop that can connect to interactiv...,"connect to interactive whiteboards, collaborat..."
519,I want a laptop with a long battery life to la...,"long battery life, lectures, teching sessions"
520,I need a lightweight and portable laptop for e...,"lightweight, portable,easy transport"

,Sentences,Keywords
0,I use my laptop as a software engineer to writ...,"software engineer, coding, debugging, testing,..."
1,"As a graphic designer, I use my laptop to crea...","graphic designer, digital art, logo design, ma..."
2,"I use my laptop as a writer to craft stories, ...","writer, storytelling, poetry, manuscript editi..."
3,"As a musician, I use my laptop to compose musi...","musician, music composition, song recording, a..."
4,I use my laptop as a gamer to play online game...,"gamer, online gaming, virtual worlds, competit..."
...,...,...
516,I want a laptop with long battery life and rel...,"long battery life, reliable performance, resea..."
517,I need a laptop to do presentations during lec...,"presentations, lectures"
518,I want a laptop that can connect to interactiv...,"connect to interactive whiteboards, collaborat..."
519,I want a laptop with a long battery life to la...,"long battery life, lectures, teching sessions"
520,I need a lightweight and portable laptop for e...,"lightweight, portable,easy transport"

In [56]:
# save DataFrame back to the laptop keywords csv file
#df.to_excel(r"C:\Users\Mazahir\Desktop\laptop_keywords_all.xlsx", index=False)